cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}-ghostfolio":
    container_name: "{ServiceName}-ghostfolio"
    image: ghostfolio/ghostfolio:2.51.0
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3333
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3333
      ACCESS_TOKEN_SALT: $GHOSTFOLIO_ACCESS_TOKEN_SALT
      DATABASE_URL: postgresql://ghostfolio:${GHOSTFOLIO_DB_PASSWORD}@ghostfolio-db:5432/ghostfolio?sslmode=prefer
      JWT_SECRET_KEY: ${GHOSTFOLIO_JWT_SECRET_KEY}
      POSTGRES_DB: ghostfolio
      POSTGRES_USER: ghostfolio
      POSTGRES_PASSWORD: ${GHOSTFOLIO_DB_PASSWORD}
      REDIS_HOST: ghostfolio-redis
      REDIS_PASSWORD: ${GHOSTFOLIO_REDIS_PASSWORD}
      REDIS_PORT: 6379
    networks:
      - tipi_main_network
    depends_on:
      ghostfolio-db:
        condition: service_healthy
      ghostfolio-redis:
        condition: service_healthy
    hostname: "{ServiceName}-ghostfolio"
  "{ServiceName}-ghostfolio-db":
    container_name: "{ServiceName}-ghostfolio-db"
    image: postgres:15.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ghostfolio
      POSTGRES_USER: ghostfolio
      POSTGRES_PASSWORD: ${GHOSTFOLIO_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -d
        - ghostfolio
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-ghostfolio-db"
  "{ServiceName}-ghostfolio-redis":
    container_name: "{ServiceName}-ghostfolio-redis"
    image: redis:7-alpine
    restart: unless-stopped
    command: |
      --requirepass ${GHOSTFOLIO_REDIS_PASSWORD}
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-ghostfolio-redis"
minVersion: 0.14.0-0
