cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-peppermint":
    image: pepperlabs/peppermint:latest
    container_name: "{ServiceName}-peppermint"
    environment:
      - DB_USERNAME=tipi
      - DB_PASSWORD=${PEPPERMINT_DB_PASSWORD}
      - DB_HOST=peppermint-db
      - API_URL={APP_PROTOCOL:-http}://${PEPPERMINT_DOMAIN_API}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
      - 8217:5003
    depends_on:
      - peppermint-db
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-peppermint"
  "{ServiceName}-peppermint-db":
    container_name: "{ServiceName}-peppermint-db"
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tipi
      - POSTGRES_PASSWORD=${PEPPERMINT_DB_PASSWORD}
      - POSTGRES_DB=peppermint
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-peppermint-db"
minVersion: 0.14.0-0
