cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: registry.gitlab.com/bockiii/deemix-docker:latest
    ports:
      - ${APP_PORT}:6595
    volumes:
      - ${APP_DATA_DIR}/data/deemix-config:/config
      - ${ROOT_FOLDER_HOST}/media:/media
      - ${ROOT_FOLDER_HOST}/media/data/torrents/deemix:/downloads
      - ${ROOT_FOLDER_HOST}/media/data/music:/music
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
