cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}":
    image: fireflyiii/data-importer:version-1
    container_name: "{ServiceName}"
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8080
    environment:
      - FIREFLY_III_URL=${FIREFLY_III_URL}
      - FIREFLY_III_ACCESS_TOKEN=${FIREFLY_III_ACCESS_TOKEN}
      - FIREFLY_III_CLIENT_ID=${FIREFLY_III_CLIENT_ID}
      - TZ=${TZ}
      - TRUSTED_PROXIES=**
      - VERIFY_TLS_SECURITY=false
      - APP_ENV=local
      - APP_DEBUG=false
      - LOG_CHANNEL=stack
      - LOG_LEVEL=info
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
