cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}":
    image: ghcr.io/gethomepage/homepage:v0.8.8
    container_name: "{ServiceName}"
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}/data/:/app/config
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
