cosmos-installer: null
version: "3.5"
services:
  "{ServiceName}":
    image: mauricenino/dashdot:5.8.3
    restart: unless-stopped
    container_name: "{ServiceName}"
    privileged: true
    ports:
      - ${APP_PORT}:3001
    volumes:
      - /:/mnt/host:ro
    environment:
      - DASHDOT_SHOW_HOST=false
      - DASHDOT_SHOW_DASH_VERSION=true
      - DASHDOT_ENABLE_CPU_TEMPS=true
      - DASHDOT_USE_IMPERIAL=true
      - DASHDOT_ALWAYS_SHOW_PERCENTAGES=true
      - DASHDOT_PAGE_TITLE=dashdot
      - DASHDOT_ACCEPT_OOKLA_EULA=true
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
