cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-linkwarden":
    image: ghcr.io/linkwarden/linkwarden:v2.4.9
    container_name: "{ServiceName}-linkwarden"
    environment:
      - DATABASE_URL=postgresql://tipi:${LINKWARDEN_DB_PASSWORD}@linkwarden-db:5432/linkwarden
      - NEXTAUTH_SECRET=${LINKWARDEN_NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}/api/v1/auth
      - NEXT_PUBLIC_DISABLE_REGISTRATION=${LINKWARDEN_NEXT_PUBLIC_DISABLE_REGISTRATION}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/linkwarden:/data/data
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - linkwarden-db
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-linkwarden"
  "{ServiceName}-linkwarden-db":
    container_name: "{ServiceName}-linkwarden-db"
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tipi
      - POSTGRES_PASSWORD=${LINKWARDEN_DB_PASSWORD}
      - POSTGRES_DB=linkwarden
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-linkwarden-db"
minVersion: 0.14.0-0
