cosmos-installer: null
version: "3"
services:
  "{ServiceName}-gotosocial":
    container_name: "{ServiceName}-gotosocial"
    image: superseriousbusiness/gotosocial:0.13.2
    user: 1000:1000
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ${APP_DATA_DIR}/data/gotosocial:/gotosocial/storage
    depends_on:
      - gotosocial-db
    environment:
      - GTS_HOST=${APP_DOMAIN}
      - GTS_LETSENCRYPT_ENABLED=false
      - GTS_DB_TYPE=postgres
      - GTS_DB_ADDRESS=gotosocial-db
      - GTS_DB_PORT=5432
      - GTS_DB_USER=tipi
      - GTS_DB_PASSWORD=${GTS_DB_PASSWORD}
      - GTS_DB_DATABASE=gotosocial-db
      - GTS_ACCOUNTS_REGISTRATION_OPEN=${GTS_ACCOUNTS_REGISTRATION_OPEN}
      - GTS_SMTP_HOST=${GTS_SMTP_HOST}
      - GTS_SMTP_PORT=${GTS_SMTP_PORT}
      - GTS_SMTP_USERNAME=${GTS_SMTP_USERNAME}
      - GTS_SMTP_PASSWORD=${GTS_SMTP_PASSWORD}
      - GTS_SMTP_FROM=${GTS_SMTP_FROM}
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-gotosocial"
  "{ServiceName}-gotosocial-db":
    container_name: "{ServiceName}-gotosocial-db"
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${GTS_DB_PASSWORD}
      POSTGRES_USER: tipi
      POSTGRES_DB: gotosocial-db
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-gotosocial-db"
minVersion: 0.14.0-0
