cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    image: privatebin/nginx-fpm-alpine:1.7.1
    container_name: "{ServiceName}"
    dns:
      - ${DNS_IP}
    ports:
      - ${APP_PORT}:8080
    restart: unless-stopped
    networks:
      - tipi_main_network
    volumes:
      - ${APP_DATA_DIR}/data:/srv/data
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
