cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-notemark":
    image: ghcr.io/enchant97/note-mark-frontend:0.11.1
    container_name: "{ServiceName}-notemark"
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-notemark"
  "{ServiceName}-notemark-backend":
    image: ghcr.io/enchant97/note-mark-backend:0.11.1
    container_name: "{ServiceName}-notemark-backend"
    restart: unless-stopped
    networks:
      - tipi_main_network
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      JWT_SECRET: ${NOTEMARK_SERVICE_SECRET}
      CORS_ORIGINS: "*"
    hostname: "{ServiceName}-notemark-backend"
  "{ServiceName}-notemark-proxy":
    container_name: "{ServiceName}-notemark-proxy"
    image: nginx:alpine
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-notemark-proxy"
minVersion: 0.14.0-0
