cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-monica":
    image: monica:4.0.0
    container_name: "{ServiceName}-monica"
    depends_on:
      - monica-db
    ports:
      - ${APP_PORT}:80
    environment:
      - APP_KEY=${MONICA_APP_KEY}
      - DB_HOST=monica-db
      - DB_USERNAME=usermonica
      - DB_PASSWORD=${MONICA_DB_PASS}
    volumes:
      - ${APP_DATA_DIR}/data:/var/www/html/storage
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-monica"
  "{ServiceName}-monica-db":
    image: mariadb:10.6.11
    container_name: "{ServiceName}-monica-db"
    environment:
      - TZ=${TZ}
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=monica
      - MARIADB_USER=usermonica
      - MARIADB_PASSWORD=${MONICA_DB_PASS}
    volumes:
      - ${APP_DATA_DIR}/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-monica-db"
minVersion: 0.14.0-0
