cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-activepieces":
    image: activepieces/activepieces:0.20.0
    container_name: "{ServiceName}-activepieces"
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    depends_on:
      activepieces-postgres:
        condition: service_healthy
      activepieces-redis:
        condition: service_healthy
    environment:
      - AP_ENGINE_EXECUTABLE_PATH=dist/packages/engine/main.js
      - AP_API_KEY=${AP_API_KEY}
      - AP_ENCRYPTION_KEY=${AP_ENCRYPTION_KEY}
      - AP_JWT_SECRET=${AP_JWT_SECRET}
      - AP_ENVIRONMENT=prod
      - AP_FRONTEND_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - AP_WEBHOOK_TIMEOUT_SECONDS=30
      - AP_TRIGGER_DEFAULT_POLL_INTERVAL=5
      - AP_POSTGRES_DATABASE=activepieces
      - AP_POSTGRES_HOST=activepieces-postgres
      - AP_POSTGRES_PORT=5432
      - AP_POSTGRES_USERNAME=tipi
      - AP_POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}
      - AP_EXECUTION_MODE=UNSANDBOXED
      - AP_REDIS_HOST=activepieces-redis
      - AP_REDIS_PORT=6379
      - AP_SANDBOX_RUN_TIME_SECONDS=600
      - AP_TELEMETRY_ENABLED=true
      - AP_TEMPLATES_SOURCE_URL="https://cloud.activepieces.com/api/v1/flow-templates"
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-activepieces"
  "{ServiceName}-activepieces-postgres":
    image: postgres:14
    restart: unless-stopped
    container_name: "{ServiceName}-activepieces-postgres"
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_DB=activepieces
      - POSTGRES_PASSWORD=${AP_POSTGRES_PASSWORD}
      - POSTGRES_USER=tipi
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-activepieces-postgres"
  "{ServiceName}-activepieces-redis":
    image: redis:7
    container_name: "{ServiceName}-activepieces-redis"
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/redis/:/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-activepieces-redis"
minVersion: 0.14.0-0
