cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-invidious":
    container_name: "{ServiceName}-invidious"
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: tipi
          password: tipi
          host: invidious-db
          port: 5432
        check_tables: true
        hmac_key: ${INVIDIOUS_HMAC_KEY}
    healthcheck:
      test: wget -nv --tries=1 --spider
        http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      invidious-db:
        condition: service_healthy
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-invidious"
  "{ServiceName}-invidious-db":
    container_name: "{ServiceName}-invidious-db"
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
      - ${APP_DATA_DIR}/data/init/sql:/config/sql
      - ${APP_DATA_DIR}/data/init/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: tipi
      POSTGRES_PASSWORD: tipi
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-invidious-db"
minVersion: 0.14.0-0
