cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    image: mrcas/kapowarr:v1.0.0-beta-3
    container_name: "{ServiceName}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/kapowarr-db:/app/db
      - ${ROOT_FOLDER_HOST}/media/downloads/kapowarr:/app/temp_downloads
      - ${ROOT_FOLDER_HOST}/media:/media
    ports:
      - ${APP_PORT}:5656
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
