cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: lscr.io/linuxserver/dokuwiki:2022-07-31a-ls158
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    environment:
      - TZ=${TZ}
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
