cosmos-installer: null
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/cross-seed/cross-seed:5.9.2
    user: 1000:1000
    restart: unless-stopped
    command: daemon
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${ROOT_FOLDER_HOST}/app-data/transmission-vpn/data/config/transmission-home/torrents:/torrents:ro
      - ${ROOT_FOLDER_HOST}/media/torrents/watch:/cross-seeds
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
