cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-ryot":
    image: ghcr.io/ignisda/ryot:v2.24.2
    container_name: "{ServiceName}-ryot"
    environment:
      - DATABASE_URL=postgres://tipi:${RYOT_DB_PASSWORD}@ryot-db:5432/ryot
      - SERVER_INSECURE_COOKIE=true
      - USERS_ALLOW_REGISTRATION=${RYOT_ALLOW_REGISTRATION}
      - VIDEO_GAMES_TWITCH_CLIENT_ID=${RYOT_VIDEO_GAMES_TWITCH_CLIENT_ID}
      - VIDEO_GAMES_TWITCH_CLIENT_SECRET= ${VIDEO_GAMES_TWITCH_CLIENT_SECRET}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - ryot-db
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-ryot"
  "{ServiceName}-ryot-db":
    container_name: "{ServiceName}-ryot-db"
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tipi
      - POSTGRES_PASSWORD=${RYOT_DB_PASSWORD}
      - POSTGRES_DB=ryot
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-ryot-db"
minVersion: 0.14.0-0
