cosmos-installer: null
version: "3"
services:
  "{ServiceName}-movary":
    image: leepeuker/movary:0.61.0
    container_name: "{ServiceName}-movary"
    environment:
      - TMDB_API_KEY=${MOVARY_TMDB_API_KEY}
      - TIMEZONE=${TZ}
      - DATABASE_MODE=mysql
      - DATABASE_MYSQL_HOST=movary-db
      - DATABASE_MYSQL_NAME=movary
      - DATABASE_MYSQL_USER=tipi
      - DATABASE_MYSQL_PASSWORD=${MOVARY_MYSQL_PASSWORD}
      - TMDB_ENABLE_IMAGE_CACHING=1
      - APPLICATION_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - PLEX_IDENTIFIER=${MOVARY_PLEX_IDENTIFIER}
      - JELLYFIN_DEVICE_ID=${MOVARY_JELLYFIN_IDENTIFIER}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/movary:/app/storage
    ports:
      - ${APP_PORT}:80
    depends_on:
      movary-db:
        condition: service_healthy
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-movary"
  "{ServiceName}-movary-migration":
    image: leepeuker/movary:0.61.0
    container_name: "{ServiceName}-movary-migration"
    command: php bin/console.php database:migration:migrate
    environment:
      - TMDB_API_KEY=${MOVARY_TMDB_API_KEY}
      - TIMEZONE=${TZ}
      - DATABASE_MODE=mysql
      - DATABASE_MYSQL_HOST=movary-db
      - DATABASE_MYSQL_NAME=movary
      - DATABASE_MYSQL_USER=tipi
      - DATABASE_MYSQL_PASSWORD=${MOVARY_MYSQL_PASSWORD}
      - TMDB_ENABLE_IMAGE_CACHING=1
      - APPLICATION_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - PLEX_IDENTIFIER=${MOVARY_PLEX_IDENTIFIER}
      - JELLYFIN_DEVICE_ID=${MOVARY_JELLYFIN_IDENTIFIER}
    volumes:
      - ${APP_DATA_DIR}/data/movary:/app/storage
    depends_on:
      movary-db:
        condition: service_healthy
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-movary-migration"
  "{ServiceName}-movary-db":
    image: mysql:8.0
    container_name: "{ServiceName}-movary-db"
    environment:
      MYSQL_DATABASE: movary
      MYSQL_USER: tipi
      MYSQL_PASSWORD: ${MOVARY_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MOVARY_MYSQL_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mysql:/var/lib/mysql
    networks:
      - tipi_main_network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      timeout: 20s
      retries: 10
    hostname: "{ServiceName}-movary-db"
minVersion: 0.14.0-0
