cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: owncast/owncast:0.1.2
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    ports:
      - ${APP_PORT}:8080
      - 1935:1935
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
