cosmos-installer: null
version: "3.8"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/wizarrrr/wizarr:3.5.1
    ports:
      - ${APP_PORT}:5690
    volumes:
      - ${APP_DATA_DIR}/data/database:/data/database
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
