cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-mixpost-pro":
    image: inovector/mixpost-pro-team:latest
    container_name: "{ServiceName}-mixpost-pro"
    environment:
      - APP_NAME=Mixpost
      - LICENSE_KEY=${MIXPOST_LICENSE_KEY}
      - APP_KEY=${MIXPOST_APP_KEY}
      - APP_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - DB_HOST=mixpost-pro-mysql
      - DB_DATABASE=mixpost
      - DB_USERNAME=tipi
      - DB_PASSWORD=${MIXPOST_MYSQL_PASSWORD}
      - REDIS_HOST=mixpost-pro-redis
      - REDIS_PASSWORD=${MIXPOST_REDIS_PASSWORD}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/mixpost-pro:/var/www/html/storage/app
    ports:
      - ${APP_PORT}:80
    depends_on:
      - mixpost-pro-mysql
      - mixpost-pro-redis
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-mixpost-pro"
  "{ServiceName}-mixpost-pro-mysql":
    image: mysql/mysql-server:8.0
    container_name: "{ServiceName}-mixpost-pro-mysql"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MIXPOST_MYSQL_PASSWORD}
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${MIXPOST_MYSQL_PASSWORD}
      - MYSQL_DATABASE=mixpost
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -p ${MIXPOST_MYSQL_PASSWORD}
      retries: 3
      timeout: 5s
    volumes:
      - ${APP_DATA_DIR}/data/mysql:/var/lib/mysql
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-mixpost-pro-mysql"
  "{ServiceName}-mixpost-pro-redis":
    image: redis:latest
    container_name: "{ServiceName}-mixpost-pro-redis"
    command: redis-server --appendonly yes --replica-read-only no --requirepass
      "${MIXPOST_REDIS_PASSWORD}"
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-mixpost-pro-redis"
minVersion: 0.14.0-0
