cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    image: lscr.io/linuxserver/booksonic-air:2201.1.0
    container_name: "{ServiceName}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - CONTEXT_PATH={APP_PROTOCOL:-http}://${APP_DOMAIN}
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${ROOT_FOLDER_HOST}/media/data/books/spoken:/audiobooks
      - ${ROOT_FOLDER_HOST}/media/data/podcasts:/podcasts
    ports:
      - ${APP_PORT}:4040
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
