cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: crccheck/hello-world:latest
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8000
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
