cosmos-installer: null
services:
  "{ServiceName}":
    user: ${TIPI_UID}:${TIPI_GID}
    container_name: "{ServiceName}"
    image: ghcr.io/recyclarr/recyclarr:6.0.2
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    environment:
      - RECYCLARR_CREATE_CONFIG=${RECYCLARR_CREATE_CONFIG-true}
      - TZ=${TZ}
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
