cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-nitter":
    image: zedeus/nitter:latest
    container_name: "{ServiceName}-nitter"
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ${APP_DATA_DIR}/data/nitter.conf:/src/nitter.conf:ro
    depends_on:
      - nitter-redis
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://localhost:8080
      interval: 1m
      timeout: 3s
    hostname: "{ServiceName}-nitter"
  "{ServiceName}-nitter-redis":
    image: redis:alpine
    container_name: "{ServiceName}-nitter-redis"
    networks:
      - tipi_main_network
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    restart: unless-stopped
    hostname: "{ServiceName}-nitter-redis"
minVersion: 0.14.0-0
