cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    image: ghcr.io/ssddanbrown/rss:v1.4.5
    container_name: "{ServiceName}"
    environment:
      - APP_NAME=Cosmos-RSS
      - APP_FEED_UPDATE_FREQUENCY=35
      - APP_LOAD_POST_THUMBNAILS=true
    volumes:
      - ${APP_DATA_DIR}/data/storage:/app/storage
    restart: unless-stopped
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
