cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: hkotel/mealie:v0.5.6
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
