cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    image: phitux/dailytxt:1.0.13
    container_name: "{ServiceName}"
    restart: unless-stopped
    environment:
      - PORT=8765
      - SECRET_KEY=${DAILYTXT_SECRET_KEY}
      - ALLOW_REGISTRATION=${DAILYTXT_ALLOW_REGISTRATION}
      - DATA_INDENT=2
      - JWT_EXP_DAYS=60
      - ENABLE_UPDATE_CHECK=True
    ports:
      - ${APP_PORT}:8765
    volumes:
      - ${APP_DATA_DIR}/data/dailytxt:/app/data/
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
