cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}":
    image: axeleroy/self-host-planning-poker:1.2.1
    container_name: "{ServiceName}"
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    networks:
      - tipi_main_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
