cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-hedgedoc":
    container_name: "{ServiceName}-hedgedoc"
    image: quay.io/hedgedoc/hedgedoc:1.9.9
    environment:
      - CMD_DB_URL=postgres://hedgedoc:${HEDGEDOC_DB_PASSWORD}@hedgedoc-db:5432/hedgedoc
      - CMD_DOMAIN=${APP_DOMAIN}
      - CMD_URL_ADDPORT=${HEDGEDOC_ADDPORT}
    volumes:
      - ${APP_DATA_DIR}/data/hedgedoc-uploads:/hedgedoc/public/uploads
    ports:
      - ${APP_PORT}:3000
    restart: always
    depends_on:
      - hedgedoc-db
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-hedgedoc"
  "{ServiceName}-hedgedoc-db":
    container_name: "{ServiceName}-hedgedoc-db"
    image: postgres:13.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=${HEDGEDOC_DB_PASSWORD}
      - POSTGRES_DB=hedgedoc
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-hedgedoc-db"
minVersion: 0.14.0-0
