cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-matrix-conduit":
    container_name: "{ServiceName}-matrix-conduit"
    image: matrixconduit/matrix-conduit:v0.6.0
    environment:
      CONDUIT_SERVER_NAME: ${APP_DOMAIN}
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit/
      CONDUIT_DATABASE_BACKEND: rocksdb
      CONDUIT_ADDRESS: 0.0.0.0
      CONDUIT_PORT: 6167
      CONDUIT_LOG: ${LOG:-warn,rocket=off,_=off,sled=off}
      CONDUIT_MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE:-20000000}
      CONDUIT_ALLOW_REGISTRATION: ${ALLOW_REGISTRATION:-false}
      CONDUIT_ALLOW_FEDERATION: ${ALLOW_FEDERATION:-false}
      CONDUIT_TRUSTED_SERVERS: ${TRUSTED_SERVERS:-[]}
      CONDUIT_ALLOW_CHECK_FOR_UPDATES: false
      CONDUIT_TURN_URIS: ${TURN_URIS:-["turn:localhost?transport=udp",
        "turn:localhost?transport=tcp"]}
      CONDUIT_TURN_SECRET: ${TURN_SECRET:-turnsecret}
      CONDUIT_CONFIG: ""
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/matrix-conduit/
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-matrix-conduit"
  "{ServiceName}-matrix-conduit-well-known":
    container_name: "{ServiceName}-matrix-conduit-well-known"
    build:
      context: nginx
      dockerfile: Dockerfile
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-matrix-conduit-well-known"
minVersion: 0.14.0-0
