cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    image: lscr.io/linuxserver/freshrss:1.23.1
    container_name: "{ServiceName}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/freshrss:/config
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
