cosmos-installer: null
version: 1.8.1-ls82
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}/data/qdirstat/config
      - ${APP_DATA_DIR}/data/qdirstat/app/data
      - /:/host:ro
    image: lscr.io/linuxserver/qdirstat:1.8.1-ls82
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
