cosmos-installer: null
version: "2"
services:
  "{ServiceName}-filestash":
    container_name: "{ServiceName}-filestash"
    image: machines/filestash:latest
    restart: unless-stopped
    environment:
      - APPLICATION_URL=${APP_DOMAIN}
      - GDRIVE_CLIENT_ID=${FILESTASH_GDRIVE_CLIENT_ID}
      - GDRIVE_CLIENT_SECRET=${FILESTASH_GDRIVE_CLIENT_SECRET}
      - DROPBOX_CLIENT_ID=${FILESTASH_DROPBOX_CLIENT_ID}
      - ONLYOFFICE_URL=http://filestash-onlyoffice
    ports:
      - ${APP_PORT}:8334
    volumes:
      - ${APP_DATA_DIR}/data:/app/data/state/
    depends_on:
      - filestash-onlyoffice
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-filestash"
  "{ServiceName}-filestash-onlyoffice":
    container_name: "{ServiceName}-filestash-onlyoffice"
    image: onlyoffice/documentserver:7.3.3.50
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-filestash-onlyoffice"
minVersion: 0.14.0-0
