cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-librephotos":
    image: reallibrephotos/librephotos-proxy:2023w48
    container_name: "{ServiceName}-librephotos"
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/scan:/data
      - ${APP_DATA_DIR}/data/protected_media:/protected_media
      - ${APP_DATA_DIR}/data/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${APP_PORT}:80
    depends_on:
      - librephotos-backend
      - librephotos-frontend
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-librephotos"
  "{ServiceName}-librephotos-db":
    image: postgres:14
    container_name: "{ServiceName}-librephotos-db"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${LIBREPHOTOS_DB_PASSWORD}
      POSTGRES_USER: tipi
      POSTGRES_DB: librephotos
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-librephotos-db"
  "{ServiceName}-librephotos-frontend":
    image: reallibrephotos/librephotos-frontend:2023w48
    container_name: "{ServiceName}-librephotos-frontend"
    restart: unless-stopped
    depends_on:
      - librephotos-backend
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-librephotos-frontend"
  "{ServiceName}-librephotos-backend":
    image: reallibrephotos/librephotos:2023w48
    container_name: "{ServiceName}-librephotos-backend"
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/scan:/data
      - ${APP_DATA_DIR}/data/protected_media:/protected_media
      - ${APP_DATA_DIR}/data/logs:/logs
      - ${APP_DATA_DIR}/data/cache:/root/.cache
    environment:
      - SECRET_KEY=${LIBREPHOTOS_SECRET_KEY}
      - BACKEND_HOST=librephotos-backend
      - ADMIN_EMAIL=${LIBREPHOTOS_EMAIL}
      - ADMIN_USERNAME=${LIBREPHOTOS_USERNAME}
      - ADMIN_PASSWORD=${LIBREPHOTOS_PASSWORD}
      - DB_BACKEND=postgresql
      - DB_NAME=librephotos
      - DB_USER=tipi
      - DB_PASS=${LIBREPHOTOS_DB_PASSWORD}
      - DB_HOST=librephotos-db
      - DB_PORT=5432
      - REDIS_HOST=librephotos-redis
      - REDIS_PORT=6379
      - ALLOW_UPLOAD=true
      - DEBUG=0
      - CSRF_TRUSTED_ORIGINS=${APP_PROTOCOL:-http}://${APP_DOMAIN},http://${INTERNAL_IP}:${APP_PORT}
    depends_on:
      librephotos-db:
        condition: service_healthy
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-librephotos-backend"
  "{ServiceName}-librephotos-redis":
    image: redis:6
    container_name: "{ServiceName}-librephotos-redis"
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-librephotos-redis"
minVersion: 0.14.0-0
