cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: lscr.io/linuxserver/mstream:v5.11.4-ls101
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}/data/mstream-config:/data
      - ${ROOT_FOLDER_HOST}/media/data/music:/music
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
