cosmos-installer: null
version: "3"
services:
  "{ServiceName}-chatgpt-ui":
    image: wongsaang/chatgpt-ui-client:v2.5.9
    container_name: "{ServiceName}-chatgpt-ui"
    environment:
      - SERVER_DOMAIN=http://chatgpt-ui-web-server
      - DEFAULT_LOCALE=en
    depends_on:
      - chatgpt-ui-web-server
    ports:
      - 8200:80
    restart: always
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-chatgpt-ui"
  "{ServiceName}-chatgpt-ui-wsgi-server":
    image: wongsaang/chatgpt-ui-wsgi-server:v2.5.2
    container_name: "{ServiceName}-chatgpt-ui-wsgi-server"
    environment:
      - APP_DOMAIN=${INTERNAL_IP}:8201
      - SERVER_WORKERS=3
      - WORKER_TIMEOUT=180
      - DB_URL=mysql://tipi:${CHATGPT_UI_DB_PASSWORD}@chatgpt-ui-db:3306/chatgptdb
      - DJANGO_SUPERUSER_USERNAME=${CHATGPT_UI_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${CHATGPT_UI_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${CHATGPT_UI_SUPERUSER_EMAIL}
      - ACCOUNT_EMAIL_VERIFICATION=none
    networks:
      - tipi_main_network
    depends_on:
      - chatgpt-ui-db
    restart: always
    hostname: "{ServiceName}-chatgpt-ui-wsgi-server"
  "{ServiceName}-chatgpt-ui-web-server":
    image: wongsaang/chatgpt-ui-web-server:v2.5.2
    container_name: "{ServiceName}-chatgpt-ui-web-server"
    environment:
      - BACKEND_URL=http://chatgpt-ui-wsgi-server:8000
    ports:
      - 8201:80
    depends_on:
      - chatgpt-ui-wsgi-server
      - chatgpt-ui-db
    networks:
      - tipi_main_network
    restart: always
    hostname: "{ServiceName}-chatgpt-ui-web-server"
  "{ServiceName}-chatgpt-ui-db":
    container_name: "{ServiceName}-chatgpt-ui-db"
    image: lscr.io/linuxserver/mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=$CHATGPT_UI_DB_PASSWORD}
      - MYSQL_DATABASE=chatgptdb
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${CHATGPT_UI_DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mysql/config:/config
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-chatgpt-ui-db"
minVersion: 0.14.0-0
