cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-bitmagnet":
    image: ghcr.io/bitmagnet-io/bitmagnet:0.7.0
    restart: unless-stopped
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
    container_name: "{ServiceName}-bitmagnet"
    environment:
      - POSTGRES_HOST=bitmagnet-db
      - POSTGRES_NAME=bitmagnet
      - POSTGRES_USER=tipi
      - POSTGRES_PASSWORD=${BITMAGNENT_DB_PASSWORD}
      - REDIS_ADDR=bitmagnet-redis:6379
    ports:
      - ${APP_PORT}:3333
      - 3334:3334/tcp
      - 3334:3334/udp
    depends_on:
      bitmagnet-db:
        condition: service_healthy
      bitmagnet-redis:
        condition: service_started
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-bitmagnet"
  "{ServiceName}-bitmagnet-db":
    container_name: "{ServiceName}-bitmagnet-db"
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${BITMAGNENT_DB_PASSWORD}
      POSTGRES_USER: tipi
      POSTGRES_DB: bitmagnet
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-bitmagnet-db"
  "{ServiceName}-bitmagnet-redis":
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    container_name: "{ServiceName}-bitmagnet-redis"
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-bitmagnet-redis"
minVersion: 0.14.0-0
