cosmos-installer: null
version: "3.3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: mrcas/mind:v1.3.3
    volumes:
      - ${APP_DATA_DIR}/data/mind-db:/app/db
    environment:
      - TZ=${TZ}
    ports:
      - ${APP_PORT}:8080
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
