cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: minio/minio:RELEASE.2023-05-04T21-44-30Z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - MINIO_DOMAIN=Host(`${APP_DOMAIN}`)
    ports:
      - 8000:9000
      - ${APP_PORT}:9001
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/minio/data:/data
    networks:
      - tipi_main_network
    command: server --console-address :9001 /data
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
