cosmos-installer: null
version: "3.8"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: alfhou/hammond:v0.0.24
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/assets:/assets
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=${HAMMOND_TZ-Europe/Paris}
    restart: unless-stopped
    networks:
      - tipi_main_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
