cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-speedtest-tracker":
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.15.3
    container_name: "{ServiceName}-speedtest-tracker"
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=speedtest-tracker-db
      - DB_PORT=5432
      - DB_DATABASE=speedtest-tracker
      - DB_USERNAME=tipi
      - DB_PASSWORD=${SPEEDTEST_TRACKER_DB_PASSWORD}
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/speedtest-tracker/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${APP_PORT}:80
      - 8212:443
    depends_on:
      - speedtest-tracker-db
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-speedtest-tracker"
  "{ServiceName}-speedtest-tracker-db":
    container_name: "{ServiceName}-speedtest-tracker-db"
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tipi
      - POSTGRES_PASSWORD=${SPEEDTEST_TRACKER_DB_PASSWORD}
      - POSTGRES_DB=speedtest-tracker
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-speedtest-tracker-db"
minVersion: 0.14.0-0
