cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}-wordpress":
    container_name: "{ServiceName}-wordpress"
    image: wordpress:6.4.3
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress-db
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-wordpress"
  "{ServiceName}-wordpress-db":
    container_name: "{ServiceName}-wordpress-db"
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-wordpress-db"
minVersion: 0.14.0-0
