cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: lscr.io/linuxserver/grav:1.7.39.4-ls97
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/grav-comfig:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
