cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    image: lscr.io/linuxserver/grocy:v4.0.3-ls215
    container_name: "{ServiceName}"
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - ${APP_PORT}:80
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
