cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-mixpost":
    image: inovector/mixpost:v1.4.0
    container_name: "{ServiceName}-mixpost"
    environment:
      - APP_NAME='Mixpost'
      - APP_KEY='${MIXPOST_APP_KEY}'
      - APP_URL='${APP_PROTOCOL:-http}://${APP_DOMAIN}'
      - DB_HOST=mixpost-mysql
      - DB_DATABASE=mixpost
      - DB_USERNAME=tipi
      - DB_PASSWORD=${MIXPOST_MYSQL_PASSWORD}
      - REDIS_HOST=mixpost-redis
      - REDIS_PASSWORD=${MIXPOST_REDIS_PASSWORD}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/mixpost-storage:/var/www/html/storage/app
      - ${APP_DATA_DIR}/data/mixpost-logs:/var/www/html/storage/logs
      - ${APP_DATA_DIR}/data/nginx/nginx.conf:/etc/nginx/sites-enabled/default
    ports:
      - ${APP_PORT}:80
    depends_on:
      - mixpost-mysql
      - mixpost-redis
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-mixpost"
  "{ServiceName}-mixpost-mysql":
    image: mysql/mysql-server:8.0
    container_name: "{ServiceName}-mixpost-mysql"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MIXPOST_MYSQL_PASSWORD}
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${MIXPOST_MYSQL_PASSWORD}
      - MYSQL_DATABASE=mixpost
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -p ${MIXPOST_MYSQL_PASSWORD}
      retries: 3
      timeout: 5s
    volumes:
      - ${APP_DATA_DIR}/data/mysql:/var/lib/mysql
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-mixpost-mysql"
  "{ServiceName}-mixpost-redis":
    image: redis:latest
    command: redis-server --appendonly yes --replica-read-only no --requirepass
      "${MIXPOST_REDIS_PASSWORD}"
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    networks:
      - tipi_main_network
    container_name: "{ServiceName}-mixpost-redis"
    hostname: "{ServiceName}-mixpost-redis"
minVersion: 0.14.0-0
