cosmos-installer: null
version: "3.8"
services:
  "{ServiceName}-calcom":
    container_name: "{ServiceName}-calcom"
    image: calcom/cal.com:v3.7.16
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    networks:
      - tipi_main_network
    depends_on:
      - db-calcom
    environment:
      - DATABASE_HOST=db-calcom
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db-calcom/calcom
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=calcom
      - LICENSE=agree
      - NEXT_PUBLIC_LICENSE_CONSENT=agree
      - NEXT_PUBLIC_WEBAPP_URL=https://${APP_DOMAIN}
      - NEXTAUTH_SECRET=${CALCOM_NEXTAUTH_SECRET}
      - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
      - MS_GRAPH_CLIENT_ID=${MS_GRAPH_CLIENT_ID}
      - MS_GRAPH_CLIENT_SECRET=${MS_GRAPH_CLIENT_SECRET}
      - ZOOM_CLIENT_ID=${ZOOM_CLIENT_ID}
      - ZOOM_CLIENT_SECRET=${ZOOM_CLIENT_SECRET}
      - GOOGLE_API_CREDENTIALS=${CALCOM_GOOGLE_API_CREDENTIALS}
      - EMAIL_FROM=${EMAIL_FROM}
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - NODE_ENV=production
    hostname: "{ServiceName}-calcom"
  "{ServiceName}-db-calcom":
    container_name: "{ServiceName}-db-calcom"
    image: postgres:16.1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=calcom
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-db-calcom"
minVersion: 0.14.0-0
