cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-wekan":
    image: ghcr.io/wekan/wekan:v7.30
    container_name: "{ServiceName}-wekan"
    environment:
      - MONGO_URL=mongodb://wekan-db:27017/wekan
      - ROOT_URL=https://${APP_DOMAIN}
      - MAIL_URL=smtp://${MAIL_ADDRESS}:${MAIL_PASSWORD}@smtp.gmail.com:587
      - MAIL_FROM=Wekan Notifications <noreply.wekan@${APP_DOMAIN}>
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/wekan:/data
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - wekan-db
    networks:
      - tipi_main_network
      - backend_network
    hostname: "{ServiceName}-wekan"
  "{ServiceName}-wekan-db":
    container_name: "{ServiceName}-wekan-db"
    image: mongo:6
    restart: unless-stopped
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/mongo:/data/db
      - ${APP_DATA_DIR}/data/dump:/dump
    networks:
      - backend_network
    hostname: "{ServiceName}-wekan-db"
networks:
  backend_network: null
minVersion: 0.14.0-0
