cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-bookstack":
    image: lscr.io/linuxserver/bookstack:23.12.20240115
    container_name: "{ServiceName}-bookstack"
    environment:
      - APP_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - DB_HOST=bookstack-db
      - DB_USERNAME=tipi
      - DB_PASSWORD=${BOOKSTACK_DB_PASS}
      - DB_DATABASE=bookstackapp
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    dns:
      - ${DNS_IP}
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - bookstack-db
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-bookstack"
  "{ServiceName}-bookstack-db":
    image: lscr.io/linuxserver/mariadb
    container_name: "{ServiceName}-bookstack-db"
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${BOOKSTACK_DB_PASS}
    volumes:
      - ${APP_DATA_DIR}/data/db:/config
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-bookstack-db"
minVersion: 0.14.0-0
