cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}":
    image: frooodle/s-pdf:0.20.2
    restart: unless-stopped
    container_name: "{ServiceName}"
    privileged: true
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ${APP_DATA_DIR}/data/trainingData:/usr/share/tesseract-ocr/5/tessdata
      - ${APP_DATA_DIR}/data/extraConfigs:/configs
      - ${APP_DATA_DIR}/data/customFiles:/customFiles/
      - ${APP_DATA_DIR}/data/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=${STIRLING_PDF_DOCKER_ENABLE_SECURITY-false}
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
