cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/ajnart/homarr:0.14.6
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/data/configs
      - ${APP_DATA_DIR}/data/icons:/app/public/icons
      - ${APP_DATA_DIR}/data/dashboard:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PASSWORD=${HOMARR_PASSWORD}
      - PGID=1000
      - TZ=${TZ}
    ports:
      - ${APP_PORT}:7575
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
