cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: samuel19982/podfetch:latest
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${APP_DATA_DIR}/data/podfetch-db:/app/db
      - ${ROOT_FOLDER_HOST}/media/data/podcasts:/app/podcasts
    environment:
      - BASIC_AUTH=true
      - USERNAME=${PODFETCH_USERNAME}
      - PASSWORD=${PODFETCH_PASSWORD}
      - POLLING_INTERVAL=60
      - SERVER_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - PODINDEX_API_KEY="${PODFETCH_PODINDEX_API_KEY}"
      - PODINDEX_API_SECRET="${PODFETCH_PODINDEX_API_SECRET}"
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
