cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-tubearchivist":
    container_name: "{ServiceName}-tubearchivist"
    restart: unless-stopped
    image: bbilly1/tubearchivist:v0.4.6
    ports:
      - ${APP_PORT}:8000
    dns:
      - ${DNS_IP}
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/youtube:/youtube
      - ${APP_DATA_DIR}/data/cache:/cache
    environment:
      - ES_URL=http://tubearchivist-es:9200
      - REDIS_HOST=tubearchivist-redis
      - TA_USERNAME=${TA_USER}
      - TA_PASSWORD=${TA_PASSWORD}
      - TA_HOST=${APP_DOMAIN}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - tubearchivist-es
      - tubearchivist-redis
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-tubearchivist"
  "{ServiceName}-tubearchivist-redis":
    image: redislabs/rejson:latest
    container_name: "{ServiceName}-tubearchivist-redis"
    restart: always
    networks:
      - tipi_main_network
    volumes:
      - ${APP_DATA_DIR}/data/redis-data:/data
    depends_on:
      - tubearchivist-es
    hostname: "{ServiceName}-tubearchivist-redis"
  "{ServiceName}-tubearchivist-es":
    image: elasticsearch:8.12.1
    container_name: "{ServiceName}-tubearchivist-es"
    restart: always
    environment:
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - path.repo=/usr/share/elasticsearch/data/snapshot
    networks:
      - tipi_main_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${APP_DATA_DIR}/data/es:/usr/share/elasticsearch/data
    expose:
      - "9200"
    hostname: "{ServiceName}-tubearchivist-es"
minVersion: 0.14.0-0
