cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    hostname: "{ServiceName}"
    image: ghcr.io/hotio/whisparr:nightly-2.0.0.313
    ports:
      - ${APP_PORT}:6969
    environment:
      - PUID=${WHISPARR_PUID-1000}
      - PGID=${WHISPARR_PGID-1000}
      - UMASK=${WHISPARR_UMASK-002}
      - TZ=${TZ}
    dns:
      - ${DNS_IP}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${APP_DATA_DIR}/data:/config
      - ${ROOT_FOLDER_HOST}/media:/media
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/6969' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - tipi_main_network
minVersion: 0.14.0-0
