cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: evanbuss/openbooks:4.5.0
    command: ./openbooks server --dir /books --port 80 --persist --name
      ${OPENBOOKS_IRC_USERNAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${ROOT_FOLDER_HOST}/media/data/books/:/books
    environment:
      - BASE_PATH=/openbooks/
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
