cosmos-installer: null
version: "3.8"
services:
  "{ServiceName}-proxitok":
    container_name: "{ServiceName}-proxitok"
    image: ghcr.io/pablouser1/proxitok:master
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8080
    environment:
      - LATTE_CACHE=/cache
      - API_CACHE=redis
      - REDIS_HOST=proxitok-redis
      - REDIS_PORT=6379
      - API_SIGNER=remote
      - API_SIGNER_URL=http://proxitok-signer:8080/signature
    volumes:
      - proxitok-cache:/cache
    depends_on:
      - proxitok-redis
      - proxitok-signer
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-proxitok"
  "{ServiceName}-proxitok-redis":
    container_name: "{ServiceName}-proxitok-redis"
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-proxitok-redis"
  "{ServiceName}-proxitok-signer":
    container_name: "{ServiceName}-proxitok-signer"
    image: ghcr.io/pablouser1/signtok:master
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-proxitok-signer"
volumes:
  proxitok-cache: null
minVersion: 0.14.0-0
