cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: gladysassistant/gladys:v4.36.0
    privileged: true
    restart: on-failure
    stop_grace_period: 1m
    network_mode: host
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8270
      - TZ=${TZ}
      - SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-production.db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data/gladysassistant:/var/lib/gladysassistant
      - /dev:/dev
      - /run/udev:/run/udev:ro
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
