cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-zipline":
    container_name: "{ServiceName}-zipline"
    image: ghcr.io/diced/zipline:3.7.8
    ports:
      - ${APP_PORT}:3000
    restart: unless-stopped
    environment:
      - CORE_RETURN_HTTPS=false
      - CORE_SECRET=${ZIPLINE_CORE_SECRET}
      - CORE_HOST=0.0.0.0
      - CORE_PORT=3000
      - CORE_DATABASE_URL=postgres://tipi:${ZIPLINE_DB_PASSWORD}@zipline-db/zipline
      - CORE_LOGGER=true
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/zipline/uploads
      - ${APP_DATA_DIR}/data/public:/zipline/public
    depends_on:
      - zipline-db
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-zipline"
  "{ServiceName}-zipline-db":
    container_name: "{ServiceName}-zipline-db"
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=tipi
      - POSTGRES_PASSWORD=${ZIPLINE_DB_PASSWORD}
      - POSTGRES_DB=zipline
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    hostname: "{ServiceName}-zipline-db"
minVersion: 0.14.0-0
