cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: shaneisrael/fireshare:v1.2.19
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/fireshare_data:/data
      - ${APP_DATA_DIR}/data/fireshare_processed:/processed
      - ${ROOT_FOLDER_HOST}/media/data/videos/fireshare_videos:/videos
    environment:
      - ADMIN_USERNAME=${FIRESHARE_USERNAME}
      - ADMIN_PASSWORD=${FIRESHARE_PASSWORD}
      - SECRET_KEY=${FIRESHARE_SECRET_KEY}
      - MINUTES_BETWEEN_VIDEO_SCANS=5
      - PUID=1000
      - PGID=1000
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
