cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    image: gotify/server:2.4.0
    container_name: "{ServiceName}"
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      - GOTIFY_DEFAULTUSER_NAME=${GOTIFY_DEFAULTUSER_NAME}
      - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}
    ports:
      - ${APP_PORT}:80
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
