cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: corentinth/it-tools:latest
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
