cosmos-installer: null
version: "3"
services:
  "{ServiceName}-planka":
    image: ghcr.io/plankanban/planka:1.15.6
    container_name: "{ServiceName}-planka"
    command: |
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/user-avatars:/app/public/user-avatars
      - ${APP_DATA_DIR}/data/project-background-images:/app/public/project-background-images
      - ${APP_DATA_DIR}/data/attachments:/app/private/attachments
    ports:
      - ${APP_PORT}:1337
    environment:
      - BASE_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - TRUST_PROXY=1
      - DATABASE_URL="postgresql://postgres@postgres/planka"
      - SECRET_KEY="${PLANKA_SECRET_KEY}"
    networks:
      - tipi_main_network
    depends_on:
      - postgres
    hostname: "{ServiceName}-planka"
  "{ServiceName}-postgres":
    image: postgres:14-alpine
    container_name: "{ServiceName}-postgres"
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: planka
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-postgres"
minVersion: 0.14.0-0
