cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}":
    image: nginx:1.25.3
    container_name: "{ServiceName}"
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
