cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: nodered/node-red:3.1.5
    restart: unless-stopped
    ports:
      - ${APP_PORT}:1880
    volumes:
      - ${APP_DATA_DIR}/data:/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
