cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: kanboard/kanboard:v1.2.35
    environment:
      - PLUGIN_INSTALLER=${PLUGIN_INSTALLER}
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/kanboard_data:/var/www/app/data
      - ${APP_DATA_DIR}/data/kanboard_plugins:/var/www/app/plugins
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
