cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/kiwix/kiwix-serve:3.5.0-2
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ${APP_DATA_DIR}/data/zim:/data
    command: "*.zim"
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
