cosmos-installer: null
version: "3"
services:
  "{ServiceName}-koillection":
    image: koillection/koillection:1.5.6
    container_name: "{ServiceName}-koillection"
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    depends_on:
      - koillection-db
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/uploads
    environment:
      - APP_DEBUG=0
      - APP_ENV=prod
      - HTTPS_ENABLED={APP_EXPOSED}
      - UPLOAD_MAX_FILESIZE=20M
      - PHP_MEMORY_LIMIT=512M
      - PHP_TZ=${TZ}
      - CORS_ALLOW_ORIGIN=*
      - JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
      - JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
      - DB_DRIVER=pdo_pgsql
      - DB_NAME=koillection
      - DB_HOST=koillection-db
      - DB_PORT=5432
      - DB_USER={KOILLECTION_DB_USER}
      - DB_PASSWORD={KOILLECTION_DB_PASSWORD}
      - DB_VERSION=15
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-koillection"
  "{ServiceName}-koillection-db":
    image: postgres:15
    container_name: "{ServiceName}-koillection-db"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=koillection
      - POSTGRES_USER={KOILLECTION_DB_USER}
      - POSTGRES_PASSWORD={KOILLECTION_DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/volumes/postgresql:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-koillection-db"
minVersion: 0.14.0-0
