cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}-umami":
    container_name: "{ServiceName}-umami"
    image: ghcr.io/umami-software/umami:postgresql-v1.40.0
    ports:
      - ${APP_PORT}:3000
    environment:
      DATABASE_URL: postgresql://umami:${DB_PASSWORD}@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: ${HASH_SALT}
    depends_on:
      - umami-db
    restart: always
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-umami"
  "{ServiceName}-umami-db":
    container_name: "{ServiceName}-umami-db"
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-umami-db"
minVersion: 0.14.0-0
