cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ghcr.io/lissy93/dashy:2.1.1
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/dashy/conf.yml:/app/public/conf.yml
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
