cosmos-installer: null
version: "3.9"
services:
  "{ServiceName}-shlink":
    container_name: "{ServiceName}-shlink"
    image: ghcr.io/shlinkio/shlink:3.7.3
    environment:
      - DEFAULT_DOMAIN=${APP_DOMAIN}
      - IS_HTTPS_ENABLED=true
      - DB_DRIVER=postgres
      - DB_HOST=shlink-db
      - DB_NAME=shlink
      - DB_USER=shlink
      - DB_PASSWORD=${SHLINK_POSTGRES_PASSWORD}
    ports:
      - ${APP_PORT}:8080
    restart: unless-stopped
    depends_on:
      - shlink-db
    volumes: []
    networks:
      - tipi_main_network
    hostname: "{ServiceName}-shlink"
  "{ServiceName}-shlink-db":
    container_name: "{ServiceName}-shlink-db"
    image: docker.io/library/postgres:16.2-alpine
    restart: unless-stopped
    networks:
      - tipi_main_network
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${SHLINK_POSTGRES_PASSWORD}
      - POSTGRES_USER=shlink
      - POSTGRES_DB=shlink
    hostname: "{ServiceName}-shlink-db"
minVersion: 0.14.0-0
