cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    image: budibase/budibase:2.19.3
    restart: unless-stopped
    container_name: "{ServiceName}"
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}:/data
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
