cosmos-installer: null
version: "3.7"
services:
  "{ServiceName}":
    image: jgraph/drawio:22.1.22
    ports:
      - ${APP_PORT}:8080
    container_name: "{ServiceName}"
    tty: true
    stdin_open: true
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
