cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: ckulka/baikal:0.9.4-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/config:/var/www/baikal/config
      - ${APP_DATA_DIR}/specific:/var/www/baikal/Specific
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
