cosmos-installer: null
version: "3"
services:
  "{ServiceName}":
    container_name: "{ServiceName}"
    image: fallenbagel/jellyseerr:1.7.0
    ports:
      - ${APP_PORT}:5055
    volumes:
      - ${APP_DATA_DIR}/data/jellyseerr-config:/app/config
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - tipi_main_network
    hostname: "{ServiceName}"
minVersion: 0.14.0-0
